# Generated by Django 6.0.1 on 2026-03-24 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agricStartup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='market_price_per_ton',
            field=models.FloatField(default=0),
        ),
    ]
