# Generated by Django 6.0.1 on 2026-03-24 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agricStartup', '0002_add_initial_crops'),
        ('agricStartup', '0002_crop_market_price_per_ton'),
    ]

    operations = [
    ]
